// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 11 May 2022 13:45:21 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "vulkan/vulkan.h"
#include "vk_wrapper.h"
#include "vk_bridge.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// PFN_vkDebugReportCallbackEXT_c918aac4 is a proxy for callback PFN_vkDebugReportCallbackEXT.
unsigned int PFN_vkDebugReportCallbackEXT_c918aac4(unsigned int flags, VkDebugReportObjectTypeEXT objectType, unsigned long int object, unsigned long int location, int messageCode, char* pLayerPrefix, char* pMessage, void* pUserData);

